# Generated by Django 6.1 on 2026-09-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
